import type { Meta, StoryObj } from '@storybook/react-vite';
import { Provider } from 'react-redux';
import { configureStore } from '@reduxjs/toolkit';
import ResultsDisplaySection from '../../src/components/AI/ResultsDisplaySection';
import { DynamicQuestionProvider } from '../../src/context/DynamicQuestionContext';
import { AIAssistantProvider } from '../../src/context/AIAssistantContext';
import questionReducer from '../../src/store/slices/questionSlice';
import aiReducer from '../../src/store/slices/aiSlice';

const mockStore = configureStore({
  reducer: {
    questions: questionReducer,
    ai: aiReducer,
  },
});

const meta: Meta<typeof ResultsDisplaySection> = {
  title: 'AI/ResultsDisplaySection',
  component: ResultsDisplaySection,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          '`ResultsDisplaySection` displays the complete results of a dynamic research question analysis. It orchestrates multiple sub-components including AI-generated charts (via HTMLRenderer), question information (QuestionInformationView), AI content generation triggers (AIContentGenerator), cost breakdowns (CostDisplay), and a data grid view (QuestionDataGridView). This component is the main output display for the dynamic question workflow.',
      },
    },
  },
  argTypes: {
    loading: {
      control: 'boolean',
      description:
        'Controls the loading state. When true and no SPARQL query exists, displays a TextSkeleton placeholder. Used during initial query generation.',
      table: {
        type: { summary: 'boolean' },
        defaultValue: { summary: 'false' },
      },
    },
    error: {
      control: 'text',
      description:
        'Error message to display in a styled error box. Shown when content generation or query execution fails. Takes precedence over other content when present.',
      table: {
        type: { summary: 'string | null' },
        defaultValue: { summary: 'null' },
      },
    },
    question: {
      control: 'text',
      description:
        'The research question text. Used to trigger AIContentGenerator when results are available but interpretations are not yet generated.',
      table: {
        type: { summary: 'string' },
      },
    },
    sparqlQuery: {
      control: 'text',
      description:
        'The SPARQL query that was executed. Used for context in AI content generation and displayed in the results section.',
      table: {
        type: { summary: 'string' },
      },
    },
    queryResults: {
      control: 'object',
      description:
        'Array of SPARQL result binding objects from the ORKG triplestore. Each object contains variable bindings with `.value` properties. Displayed in QuestionDataGridView and used for chart generation.',
      table: {
        type: { summary: 'Record<string, unknown>[]' },
        defaultValue: { summary: '[]' },
      },
    },
    chartHtml: {
      control: 'text',
      description:
        'HTML string containing a Chart.js visualization. Rendered via HTMLRenderer in an iframe for isolation. Generated by AI based on query results.',
      table: {
        type: { summary: 'string' },
      },
    },
    questionInterpretation: {
      control: 'text',
      description:
        'AI-generated interpretation of the research question. Explains the significance and context of the question in the research domain.',
      table: {
        type: { summary: 'string' },
      },
    },
    dataCollectionInterpretation: {
      control: 'text',
      description:
        'AI-generated interpretation of the data collection process. Explains how the SPARQL query retrieves relevant data from ORKG.',
      table: {
        type: { summary: 'string' },
      },
    },
    dataAnalysisInterpretation: {
      control: 'text',
      description:
        'AI-generated interpretation of the analysis results. Provides insights, patterns, and conclusions from the query results.',
      table: {
        type: { summary: 'string' },
      },
    },
    dynamicQuery: {
      control: 'object',
      description:
        'DynamicQuery object containing question metadata, chart settings, and data analysis information. Structure mirrors the Query type from queries_chart_info. Required for QuestionInformationView display.',
      table: {
        type: { summary: 'DynamicQuery | null' },
      },
    },
    costs: {
      control: 'object',
      description:
        'Array of CostBreakdown objects tracking AI API usage. Each entry includes model, provider, token counts, costs, and the section that incurred the cost. Displayed via CostDisplay component.',
      table: {
        type: { summary: 'CostBreakdown[]' },
        defaultValue: { summary: '[]' },
      },
    },
    onContentGenerated: {
      action: 'contentGenerated',
      description:
        'Callback fired when AIContentGenerator completes. Receives chartHtml, chartDescription, and three interpretation strings. Parent should update state with generated content.',
      table: {
        type: {
          summary:
            '(chartHtml, chartDesc, questionInterp, dataCollectionInterp, dataAnalysisInterp) => void',
        },
      },
    },
    onError: {
      action: 'error',
      description:
        'Callback fired when an error occurs during content generation. Receives the error message string.',
      table: {
        type: { summary: '(error: string) => void' },
      },
    },
    onChartHtmlChange: {
      action: 'chartHtmlChanged',
      description:
        'Callback fired when the chart HTML is modified via HTMLRenderer editing. Receives the updated HTML string.',
      table: {
        type: { summary: '(html: string) => void' },
      },
    },
  },
  decorators: [
    (Story) => (
      <Provider store={mockStore}>
        <AIAssistantProvider>
          <DynamicQuestionProvider>
            <div style={{ maxWidth: '1200px', padding: '20px' }}>
              <Story />
            </div>
          </DynamicQuestionProvider>
        </AIAssistantProvider>
      </Provider>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof ResultsDisplaySection>;

// research question
const sampleQuestion =
  'How has the number of empirical studies in Requirements Engineering evolved over the years?';

// SPARQL query
const sampleSparqlQuery = `PREFIX orkgp: <http://orkg.org/orkg/predicate/>
PREFIX orkgr: <http://orkg.org/orkg/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?year (COUNT(DISTINCT ?paper) AS ?paperCount)
WHERE {
  ?contribution orkgp:P31 orkgr:R54312 .
  ?paper orkgp:P31 ?contribution .
  ?paper orkgp:P29 ?year .
}
GROUP BY ?year
ORDER BY ?year`;

// SPARQL query results from ORKG (simplified for display)
const sampleQueryResults = [
  { year: '2018', paperCount: '45' },
  { year: '2019', paperCount: '62' },
  { year: '2020', paperCount: '78' },
  { year: '2021', paperCount: '95' },
  { year: '2022', paperCount: '124' },
  { year: '2023', paperCount: '156' },
];

// DynamicQuery object matching the Query interface
const sampleDynamicQuery = {
  title: 'Empirical Studies Evolution',
  id: 1,
  uid: 'empirical-evolution-001',
  dataAnalysisInformation: {
    question: sampleQuestion,
    questionExplanation:
      'This research question investigates the temporal trends in empirical research within Requirements Engineering. Understanding publication patterns helps identify growing research interest and maturity of empirical methods in the field.',
    requiredDataForAnalysis: [
      'Publication year of each paper',
      'Paper classification as empirical study',
      'Link to KG-EmpiRE template contributions',
    ],
    dataAnalysis: [
      'Count distinct papers per year',
      'Calculate year-over-year growth rates',
      'Identify trend patterns (linear, exponential)',
    ],
    dataInterpretation: [
      'Consistent upward trend indicates growing adoption of empirical methods',
      '247% growth from 2018 to 2023 shows accelerating research interest',
      'Post-2020 acceleration may correlate with increased focus on evidence-based RE',
    ],
  },
  chartSettings: {
    series: [{ dataKey: 'paperCount', label: 'Papers' }],
    colors: ['#e86161'],
    yAxis: [{ label: 'Number of Papers', dataKey: 'paperCount' }],
    height: 400,
    sx: {},
  },
  chartType: 'bar' as const,
  gridOptions: {
    defaultColumns: ['year', 'paperCount'],
    defaultGroupBy: 'year',
  },
};

// cost breakdown for AI operations
const sampleCosts = [
  {
    model: 'gpt-4-turbo',
    provider: 'openai' as const,
    promptTokens: 2450,
    completionTokens: 890,
    totalTokens: 3340,
    inputCost: 0.0245,
    outputCost: 0.0267,
    totalCost: 0.0512,
    section: 'SPARQL Query Generation',
  },
  {
    model: 'gpt-4-turbo',
    provider: 'openai' as const,
    promptTokens: 3200,
    completionTokens: 1450,
    totalTokens: 4650,
    inputCost: 0.032,
    outputCost: 0.0435,
    totalCost: 0.0755,
    section: 'Chart Generation',
  },
  {
    model: 'gpt-4-turbo',
    provider: 'openai' as const,
    promptTokens: 1800,
    completionTokens: 650,
    totalTokens: 2450,
    inputCost: 0.018,
    outputCost: 0.0195,
    totalCost: 0.0375,
    section: 'Data Interpretation',
  },
];

// chart HTML (simplified for story)
const sampleChartHtml = `<div style="width: 100%; height: 400px; display: flex; align-items: center; justify-content: center; background: linear-gradient(135deg, #f5f7fa 0%, #e4e8ec 100%); border-radius: 8px;">
  <div style="text-align: center; color: #666;">
    <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
      <line x1="3" y1="9" x2="21" y2="9"></line>
      <line x1="9" y1="21" x2="9" y2="9"></line>
    </svg>
    <p style="margin-top: 12px; font-size: 14px;">Chart.js Bar Chart Visualization</p>
    <p style="font-size: 12px; color: #999;">Showing empirical studies by year (2018-2023)</p>
  </div>
</div>`;

export const Default: Story = {
  args: {
    loading: false,
    error: null,
    question: sampleQuestion,
    sparqlQuery: sampleSparqlQuery,
    queryResults: sampleQueryResults,
    chartHtml: '',
    questionInterpretation: '',
    dataCollectionInterpretation: '',
    dataAnalysisInterpretation: '',
    dynamicQuery: sampleDynamicQuery,
    costs: [],
  },
  parameters: {
    docs: {
      description: {
        story:
          'Default view with query results and dynamic query information, before AI content generation. The AIContentGenerator component will be triggered to generate chart and interpretations. Shows QuestionInformationView with research question metadata.',
      },
    },
  },
};

export const WithChartAndInterpretations: Story = {
  args: {
    loading: false,
    error: null,
    question: sampleQuestion,
    sparqlQuery: sampleSparqlQuery,
    queryResults: sampleQueryResults,
    chartHtml: sampleChartHtml,
    questionInterpretation:
      "This research question investigates the temporal evolution of empirical research practices in Requirements Engineering, providing insights into the field's methodological maturity.",
    dataCollectionInterpretation:
      'Data was collected from the ORKG knowledge graph by querying papers linked to the KG-EmpiRE template (R54312), which indexes empirical studies in Requirements Engineering.',
    dataAnalysisInterpretation:
      'The analysis reveals a 247% increase in empirical studies from 2018 (45 papers) to 2023 (156 papers). The compound annual growth rate (CAGR) of approximately 28% indicates sustained and accelerating interest in empirical RE research.',
    dynamicQuery: sampleDynamicQuery,
    costs: sampleCosts,
  },
  parameters: {
    docs: {
      description: {
        story:
          'Complete results display with AI-generated chart, all three interpretations, and cost breakdown. This represents the final state after successful AI content generation. The CostDisplay shows token usage and costs for each AI operation.',
      },
    },
  },
};

export const WithError: Story = {
  args: {
    loading: false,
    error:
      'Failed to generate analysis content. The AI service returned an error: Rate limit exceeded. Please wait a few minutes and try again, or check your API key configuration.',
    question: sampleQuestion,
    sparqlQuery: sampleSparqlQuery,
    queryResults: [],
    chartHtml: '',
    questionInterpretation: '',
    dataCollectionInterpretation: '',
    dataAnalysisInterpretation: '',
    dynamicQuery: null,
    costs: [],
  },
  parameters: {
    docs: {
      description: {
        story:
          'Error state displaying a styled error message when content generation fails. Common causes include API rate limits, invalid API keys, or service unavailability.',
      },
    },
  },
};
